export const GET_APPOINTMENTS =
  "GET_APPOINTMENTS";

export const SET_APPOINTMENTS =
  "SET_APPOINTMENTS";

export const CREATE_APPOINTMENT =
  "CREATE_APPOINTMENT";

export const ADD_APPOINTMENT =
  "ADD_APPOINTMENT";

export const DELETE_APPOINTMENT =
  "DELETE_APPOINTMENT";
  export const REMOVE_APPOINTMENT =
  "REMOVE_APPOINTMENT";

export const APPOINTMENT_ERROR =
  "APPOINTMENT_ERROR";